### PR TITLE
Upgrade to svelte 4

### PR DESCRIPTION
**Pull request by nwaughachukwuma**
### Summary

1. update svelte related dependencies
2. use the recommended eslint plugin and parser
3. integrate vitest for testing, in place of jest
   - vitest is blazing fast and easy to setup
   - https://vitest.dev/
   - https://testing-library.com/docs/svelte-testing-library/intro

cc @pablo-abc

### CODE REVIEW

**Comment by nwaughachukwuma** [comment]
@pablo-abc, the PR is now ready for review

**Comment by pablo-abc** [comment]
Actually appreciate moving to Vitest! I've wanted to do it for a while. Thanks for the pull request!

**Comment by pablo-abc** [comment]
It's failing to run! If you can update the workflow files to include node 16.x and 18.x instead of 12 and 14, I think that'd fix it

**Comment by nwaughachukwuma** [comment]
Done in b6d1abe

**Review by pablo-abc — APPROVED** [review]

**Pull request merged**
